name: Build Check

permissions:
  contents: write

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Get branch name from PR
        run: |
          echo "BRANCH_NAME=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV

      - name: Deploy to GitHub Pages
        run: |
          mkdir "${{ env.BRANCH_NAME }}"
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          cp -r ./public/* "${{ env.BRANCH_NAME }}"/
          git add .
          git commit -m "Deploy to GitHub Pages" || exit 0
          git push origin gh-pages
